# Generated by Django 3.1.4 on 2020-12-07 20:42

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='rich_t',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
